version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t udagram-api-feed:latest -f udagram-api-feed/Dockerfile .
            docker build -t udagram-api-user:latest -f udagram-api-user/Dockerfile .
            docker build -t reverseproxy:latest -f reverseproxy/Dockerfile .
            docker build -t udagram-frontend:latest -f udagram-frontend/Dockerfile .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push "$DOCKER_USERNAME"/udagram-api-feed
            docker push "$DOCKER_USERNAME"/udagram-api-user
            docker push "$DOCKER_USERNAME"/reverseproxy
            docker push "$DOCKER_USERNAME"/udagram-frontend