version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t udagram-api-feed .
            docker build -t reverseproxy .
            docker build -t udagram-api-user .
            docker build -t udagram-frontend .
            docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed
            docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user
            docker tag reverseproxy "$DOCKER_USERNAME"/reverseproxy
            docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push "$DOCKER_USERNAME"/udagram-api-feed
            docker push "$DOCKER_USERNAME"/udagram-api-user
            docker push "$DOCKER_USERNAME"/reverseproxy
            docker push "$DOCKER_USERNAME"/udagram-frontend