version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t reverseproxy ./reverseproxy
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-api-feed saherabdelaziz/udagram-api-feed:v1
            docker tag udagram-api-feed saherabdelaziz/udagram-api-user:v1
            docker tag udagram-api-feed saherabdelaziz/reverseproxy:v1
            docker tag udagram-api-feed saherabdelaziz/udagram-frontend:v1
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push "$DOCKER_USERNAME"/udagram-api-feed
            docker push "$DOCKER_USERNAME"/udagram-api-user
            docker push "$DOCKER_USERNAME"/reverseproxy
            docker push "$DOCKER_USERNAME"/udagram-frontend