version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-api-feed saherabdelaziz/udagram-api-feed:v1
            docker tag udagram-reverseproxy saherabdelaziz/udagram-api-user:v1
            docker tag udagram-api-user saherabdelaziz/udagram-reverseproxy:v1
            docker tag udagram-frontend saherabdelaziz/udagram-frontend:v1
      - run:
          name: Push Docker image
          command: |
            docker login -u saherabdelaziz -p dckr_pat_SGktnY3yam10V501NWLaTSS2LXY
            docker push saherabdelaziz/udagram-api-feed
            docker push saherabdelaziz/udagram-api-user
            docker push saherabdelaziz/udagram-reverseproxy
            docker push saherabdelaziz/udagram-frontend