apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: saherabdelaziz/udagram-reverseproxy:v2
        name: reverseproxyv1
        imagePullPolicy: Always         
        ports:
        - containerPort: 8080
      restartPolicy: Always